<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): users
 * Generated at: 2026-07-11 09:27:43
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class AdminUserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->delete();


        DB::table('users')->insert([
            [
                'id' => 22,
                'name' => 'Admin',
                'email' => 'admin@example.com',
                'email_verified_at' => '2026-07-10 18:00:49',
                'password' => '$2y$12$md2TyDdLwNmDmv58XPGjkuRTe4oFtGPWN44jP1EspmraqAjHKXY2G',
                'phone' => null,
                'phone_verified_at' => null,
                'company' => null,
                'country' => null,
                'locale' => 'fa',
                'preferred_language' => 'fa',
                'is_active' => 1,
                'last_login_at' => null,
                'last_login_ip' => null,
                'remember_token' => null,
                'created_at' => '2026-07-10 18:00:49',
                'updated_at' => '2026-07-10 18:00:49',
                'deleted_at' => null
            ],
            [
                'id' => 23,
                'name' => 'Super User',
                'email' => 'Nazari.Moradkhani@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$qjJUmbkZ2Bm6JFpzfWFRJeyI8kMrIg6mAUmebDdPrBpzrWv0B.WfS',
                'phone' => null,
                'phone_verified_at' => null,
                'company' => null,
                'country' => null,
                'locale' => 'fa',
                'preferred_language' => 'fa',
                'is_active' => 1,
                'last_login_at' => '2026-07-11 09:25:47',
                'last_login_ip' => '127.0.0.1',
                'remember_token' => null,
                'created_at' => '2026-07-10 18:00:49',
                'updated_at' => '2026-07-11 09:25:47',
                'deleted_at' => null
            ]
        ]);

    }
}
