<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Attribute;

class AttributeSeeder extends Seeder
{
    public function run(): void
    {
        $attributes = [

            // ── 1. Color ────────────────────────────────────────
            [
                'key'   => 'color',
                'type'  => 'select',
                'label' => [
                    'fa' => 'رنگ',
                    'en' => 'Color',
                    'ar' => 'اللون',
                    'hi' => 'रंग',
                    'it' => 'Colore',
                    'zh' => '颜色',
                    'tr' => 'Renk',
                ],
                'group' => [
                    'fa' => 'ظاهر و رنگ',
                    'en' => 'Appearance & Color',
                    'ar' => 'المظهر واللون',
                    'hi' => 'दिखावट और रंग',
                    'it' => 'Aspetto e Colore',
                    'zh' => '外观与颜色',
                    'tr' => 'Görünüm ve Renk',
                ],
                'options' => [
                    ['key' => 'white',  'label' => ['fa' => 'سفید',   'en' => 'White',  'ar' => 'أبيض',   'hi' => 'सफ़ेद',  'it' => 'Bianco', 'zh' => '白色', 'tr' => 'Beyaz']],
                    ['key' => 'cream',  'label' => ['fa' => 'کرم',    'en' => 'Cream',  'ar' => 'كريمي',  'hi' => 'क्रीम',  'it' => 'Crema', 'zh' => '奶油色', 'tr' => 'Krem']],
                    ['key' => 'honey',  'label' => ['fa' => 'عسلی',   'en' => 'Honey',  'ar' => 'عسلي',   'hi' => 'शहद',    'it' => 'Miele', 'zh' => '蜂蜜色', 'tr' => 'Bal Rengi']],
                    ['key' => 'beige',  'label' => ['fa' => 'بژ',     'en' => 'Beige',  'ar' => 'بيج',    'hi' => 'बेज',    'it' => 'Beige', 'zh' => '米色', 'tr' => 'Bej']],
                    ['key' => 'gray',   'label' => ['fa' => 'طوسی',   'en' => 'Gray',   'ar' => 'رمادي',  'hi' => 'धूसर',   'it' => 'Grigio', 'zh' => '灰色', 'tr' => 'Gri']],
                    ['key' => 'black',  'label' => ['fa' => 'مشکی',   'en' => 'Black',  'ar' => 'أسود',   'hi' => 'काला',   'it' => 'Nero', 'zh' => '黑色', 'tr' => 'Siyah']],
                    ['key' => 'red',    'label' => ['fa' => 'قرمز',   'en' => 'Red',    'ar' => 'أحمر',   'hi' => 'लाल',    'it' => 'Rosso', 'zh' => '红色', 'tr' => 'Kırmızı']],
                    ['key' => 'pink',   'label' => ['fa' => 'صورتی',  'en' => 'Pink',   'ar' => 'وردي',   'hi' => 'गुलाबी', 'it' => 'Rosa', 'zh' => '粉色', 'tr' => 'Pembe']],
                    ['key' => 'green',  'label' => ['fa' => 'سبز',    'en' => 'Green',  'ar' => 'أخضر',   'hi' => 'हरा',    'it' => 'Verde', 'zh' => '绿色', 'tr' => 'Yeşil']],
                    ['key' => 'gold',   'label' => ['fa' => 'طلایی',  'en' => 'Gold',   'ar' => 'ذهبي',   'hi' => 'सुनहरा', 'it' => 'Oro', 'zh' => '金色', 'tr' => 'Altın']],
                    ['key' => 'brown',  'label' => ['fa' => 'قهوه‌ای', 'en' => 'Brown', 'ar' => 'بني',    'hi' => 'भूरा',   'it' => 'Marrone', 'zh' => '棕色', 'tr' => 'Kahverengi']],
                ],
                'unit'                 => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 1,
            ],

            // ── 2. Surface Finish ─────────────────────────────────
            [
                'key'   => 'surface_finish',
                'type'  => 'select',
                'label' => [
                    'fa' => 'نوع پرداخت سطح',
                    'en' => 'Surface Finish',
                    'ar' => 'تشطيب السطح',
                    'hi' => 'सतह फिनिश',
                    'it' => 'Finitura Superficie',
                    'zh' => '表面处理',
                    'tr' => 'Yüzey İşlemi',
                ],
                'group' => [
                    'fa' => 'ظاهر و رنگ',
                    'en' => 'Appearance & Color',
                    'ar' => 'المظهر واللون',
                    'hi' => 'दिखावट और रंग',
                    'it' => 'Aspetto e Colore',
                    'zh' => '外观与颜色',
                    'tr' => 'Görünüm ve Renk',
                ],
                'options' => [
                    ['key' => 'polished',  'label' => ['fa' => 'پولیش',     'en' => 'Polished',  'ar' => 'مصقول',     'hi' => 'पॉलिश्ड',     'it' => 'Lucidato', 'zh' => '抛光', 'tr' => 'Cilalı']],
                    ['key' => 'honed',     'label' => ['fa' => 'هانیکام',   'en' => 'Honed',     'ar' => 'مصنفر',     'hi' => 'होन्ड',       'it' => 'Levigato', 'zh' => '亚光', 'tr' => 'Honlanmış']],
                    ['key' => 'flamed',    'label' => ['fa' => 'فلیم',      'en' => 'Flamed',    'ar' => 'محروق',     'hi' => 'फ्लेम्ड',     'it' => 'Fiammato', 'zh' => '火烧面', 'tr' => 'Yakma']],
                    ['key' => 'bush_hammered', 'label' => ['fa' => 'بوشهمر', 'en' => 'Bush-hammered', 'ar' => 'مطروق', 'hi' => 'बश-हैमर्ड', 'it' => 'Bocciardato', 'zh' => '荔枝面', 'tr' => 'Bujarda']],
                    ['key' => 'sandblasted', 'label' => ['fa' => 'ساتنی (سندبلاست)', 'en' => 'Sandblasted', 'ar' => 'منفوخ بالرمل', 'hi' => 'सैंडब्लास्टेड', 'it' => 'Sabbiato', 'zh' => '喷砂面', 'tr' => 'Kumlanmış']],
                    ['key' => 'antique',   'label' => ['fa' => 'آنتیک',     'en' => 'Antique',   'ar' => 'أنتيك',     'hi' => 'प्राचीन',     'it' => 'Anticato', 'zh' => '仿古面', 'tr' => 'Antik']],
                    ['key' => 'rustic',    'label' => ['fa' => 'روستیک',    'en' => 'Rustic',    'ar' => 'ريفي',      'hi' => 'देहाती',      'it' => 'Rustico', 'zh' => '乡村面', 'tr' => 'Rustik']],
                    ['key' => 'natural_split', 'label' => ['fa' => 'لاشه (شکافت طبیعی)', 'en' => 'Natural Split', 'ar' => 'مشقوق طبيعي', 'hi' => 'प्राकृतिक विभाजन', 'it' => 'Spaccatura Naturale', 'zh' => '自然劈裂面', 'tr' => 'Doğal Yarılmış']],
                ],
                'unit'                 => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 2,
            ],

            // ── 3. Length ─────────────────────────────────────────
            [
                'key'   => 'length',
                'type'  => 'number',
                'label' => [
                    'fa' => 'طول',
                    'en' => 'Length',
                    'ar' => 'الطول',
                    'hi' => 'लंबाई',
                    'it' => 'Lunghezza',
                    'zh' => '长度',
                    'tr' => 'Uzunluk',
                ],
                'group' => [
                    'fa' => 'ابعاد و وزن',
                    'en' => 'Dimensions & Weight',
                    'ar' => 'الأبعاد والوزن',
                    'hi' => 'आयाम और वजन',
                    'it' => 'Dimensioni e Peso',
                    'zh' => '尺寸与重量',
                    'tr' => 'Boyut ve Ağırlık',
                ],
                'unit'                 => 'cm',
                'min_value'            => 0,
                'max_value'            => 500,
                'step_value'           => 0.5,
                'default_value'        => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => true,
                'is_active'            => true,
                'sort_order'           => 3,
            ],

            // ── 4. Width ──────────────────────────────────────────
            [
                'key'   => 'width',
                'type'  => 'number',
                'label' => [
                    'fa' => 'عرض',
                    'en' => 'Width',
                    'ar' => 'العرض',
                    'hi' => 'चौड़ाई',
                    'it' => 'Larghezza',
                    'zh' => '宽度',
                    'tr' => 'Genişlik',
                ],
                'group' => [
                    'fa' => 'ابعاد و وزن',
                    'en' => 'Dimensions & Weight',
                    'ar' => 'الأبعاد والوزن',
                    'hi' => 'आयाम और वजन',
                    'it' => 'Dimensioni e Peso',
                    'zh' => '尺寸与重量',
                    'tr' => 'Boyut ve Ağırlık',
                ],
                'unit'                 => 'cm',
                'min_value'            => 0,
                'max_value'            => 500,
                'step_value'           => 0.5,
                'default_value'        => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => true,
                'is_active'            => true,
                'sort_order'           => 4,
            ],

            // ── 5. Thickness ──────────────────────────────────────
            [
                'key'   => 'thickness',
                'type'  => 'number',
                'label' => [
                    'fa' => 'ضخامت',
                    'en' => 'Thickness',
                    'ar' => 'السماكة',
                    'hi' => 'मोटाई',
                    'it' => 'Spessore',
                    'zh' => '厚度',
                    'tr' => 'Kalınlık',
                ],
                'group' => [
                    'fa' => 'ابعاد و وزن',
                    'en' => 'Dimensions & Weight',
                    'ar' => 'الأبعاد والوزن',
                    'hi' => 'आयाम और वजन',
                    'it' => 'Dimensioni e Peso',
                    'zh' => '尺寸与重量',
                    'tr' => 'Boyut ve Ağırlık',
                ],
                'unit'                 => 'cm',
                'min_value'            => 0,
                'max_value'            => 30,
                'step_value'           => 0.5,
                'default_value'        => 2,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 5,
            ],

            // ── 6. Weight ─────────────────────────────────────────
            [
                'key'   => 'weight',
                'type'  => 'number',
                'label' => [
                    'fa' => 'وزن',
                    'en' => 'Weight',
                    'ar' => 'الوزن',
                    'hi' => 'वजन',
                    'it' => 'Peso',
                    'zh' => '重量',
                    'tr' => 'Ağırlık',
                ],
                'group' => [
                    'fa' => 'ابعاد و وزن',
                    'en' => 'Dimensions & Weight',
                    'ar' => 'الأبعاد والوزن',
                    'hi' => 'आयाम और वजन',
                    'it' => 'Dimensioni e Peso',
                    'zh' => '尺寸与重量',
                    'tr' => 'Boyut ve Ağırlık',
                ],
                'unit'                 => 'kg',
                'min_value'            => 0,
                'max_value'            => null,
                'step_value'           => 1,
                'default_value'        => null,
                'is_filterable'        => false,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 6,
            ],

            // ── 7. Block Volume ───────────────────────────────────
            [
                'key'   => 'block_volume',
                'type'  => 'number',
                'label' => [
                    'fa' => 'حجم بلوک',
                    'en' => 'Block Volume',
                    'ar' => 'حجم الكتلة',
                    'hi' => 'ब्लॉक आयतन',
                    'it' => 'Volume Blocco',
                    'zh' => '荒料体积',
                    'tr' => 'Blok Hacmi',
                ],
                'group' => [
                    'fa' => 'ابعاد و وزن',
                    'en' => 'Dimensions & Weight',
                    'ar' => 'الأبعاد والوزن',
                    'hi' => 'आयाम और वजन',
                    'it' => 'Dimensioni e Peso',
                    'zh' => '尺寸与重量',
                    'tr' => 'Boyut ve Ağırlık',
                ],
                'unit'                 => 'm3',
                'min_value'            => 0,
                'max_value'            => null,
                'step_value'           => 0.01,
                'default_value'        => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 7,
            ],

            // ── 8. Mine / Quarry Origin ────────────────────────────
            [
                'key'   => 'quarry_origin',
                'type'  => 'text',
                'label' => [
                    'fa' => 'معدن استخراج',
                    'en' => 'Quarry Origin',
                    'ar' => 'منشأ المحجر',
                    'hi' => 'खदान मूल',
                    'it' => 'Origine Cava',
                    'zh' => '矿场产地',
                    'tr' => 'Ocak Kökeni',
                ],
                'group' => [
                    'fa' => 'منشأ و کیفیت',
                    'en' => 'Origin & Quality',
                    'ar' => 'المنشأ والجودة',
                    'hi' => 'मूल और गुणवत्ता',
                    'it' => 'Origine e Qualità',
                    'zh' => '产地与品质',
                    'tr' => 'Köken ve Kalite',
                ],
                'unit'                 => null,
                'default_value'        => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 8,
            ],

            // ── 9. Country of Origin ───────────────────────────────
            [
                'key'   => 'country_of_origin',
                'type'  => 'text',
                'label' => [
                    'fa' => 'کشور مبدأ',
                    'en' => 'Country of Origin',
                    'ar' => 'بلد المنشأ',
                    'hi' => 'मूल देश',
                    'it' => 'Paese di Origine',
                    'zh' => '原产国',
                    'tr' => 'Menşe Ülke',
                ],
                'group' => [
                    'fa' => 'منشأ و کیفیت',
                    'en' => 'Origin & Quality',
                    'ar' => 'المنشأ والجودة',
                    'hi' => 'मूल और गुणवत्ता',
                    'it' => 'Origine e Qualità',
                    'zh' => '产地与品质',
                    'tr' => 'Köken ve Kalite',
                ],
                'unit'                 => null,
                'default_value'        => 'Iran',
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 9,
            ],

            // ── 10. Quality Grade ───────────────────────────────────
            [
                'key'   => 'quality_grade',
                'type'  => 'select',
                'label' => [
                    'fa' => 'درجه کیفیت',
                    'en' => 'Quality Grade',
                    'ar' => 'درجة الجودة',
                    'hi' => 'गुणवत्ता ग्रेड',
                    'it' => 'Grado di Qualità',
                    'zh' => '质量等级',
                    'tr' => 'Kalite Derecesi',
                ],
                'group' => [
                    'fa' => 'منشأ و کیفیت',
                    'en' => 'Origin & Quality',
                    'ar' => 'المنشأ والجودة',
                    'hi' => 'मूल और गुणवत्ता',
                    'it' => 'Origine e Qualità',
                    'zh' => '产地与品质',
                    'tr' => 'Köken ve Kalite',
                ],
                'options' => [
                    ['key' => 'premium',  'label' => ['fa' => 'ممتاز (درجه یک)', 'en' => 'Premium (Grade A)', 'ar' => 'ممتاز (الدرجة أ)', 'hi' => 'प्रीमियम (ग्रेड ए)', 'it' => 'Premium (Grado A)', 'zh' => '优质（一级）', 'tr' => 'Premium (A Sınıfı)']],
                    ['key' => 'standard', 'label' => ['fa' => 'استاندارد (درجه دو)', 'en' => 'Standard (Grade B)', 'ar' => 'قياسي (الدرجة ب)', 'hi' => 'स्टैंडर्ड (ग्रेड बी)', 'it' => 'Standard (Grado B)', 'zh' => '标准（二级）', 'tr' => 'Standart (B Sınıfı)']],
                    ['key' => 'commercial', 'label' => ['fa' => 'تجاری (درجه سه)', 'en' => 'Commercial (Grade C)', 'ar' => 'تجاري (الدرجة ج)', 'hi' => 'कमर्शियल (ग्रेड सी)', 'it' => 'Commerciale (Grado C)', 'zh' => '商用（三级）', 'tr' => 'Ticari (C Sınıfı)']],
                ],
                'unit'                 => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 10,
            ],

            // ── 11. Pattern / Veining ───────────────────────────────
            [
                'key'   => 'pattern',
                'type'  => 'select',
                'label' => [
                    'fa' => 'نوع طرح و رگه',
                    'en' => 'Pattern / Veining',
                    'ar' => 'النمط / التعريق',
                    'hi' => 'पैटर्न / वेनिंग',
                    'it' => 'Motivo / Venatura',
                    'zh' => '花纹/纹理',
                    'tr' => 'Desen / Damar',
                ],
                'group' => [
                    'fa' => 'ظاهر و رنگ',
                    'en' => 'Appearance & Color',
                    'ar' => 'المظهر واللون',
                    'hi' => 'दिखावट और रंग',
                    'it' => 'Aspetto e Colore',
                    'zh' => '外观与颜色',
                    'tr' => 'Görünüm ve Renk',
                ],
                'options' => [
                    ['key' => 'uniform',  'label' => ['fa' => 'یکدست', 'en' => 'Uniform', 'ar' => 'متجانس', 'hi' => 'समान', 'it' => 'Uniforme', 'zh' => '均匀', 'tr' => 'Homojen']],
                    ['key' => 'veined',   'label' => ['fa' => 'رگه‌دار', 'en' => 'Veined', 'ar' => 'معرّق', 'hi' => 'धारीदार', 'it' => 'Venato', 'zh' => '带纹理', 'tr' => 'Damarlı']],
                    ['key' => 'wavy',     'label' => ['fa' => 'موجی', 'en' => 'Wavy', 'ar' => 'متموج', 'hi' => 'लहरदार', 'it' => 'Ondulato', 'zh' => '波浪状', 'tr' => 'Dalgalı']],
                    ['key' => 'spotted',  'label' => ['fa' => 'لکه‌دار', 'en' => 'Spotted', 'ar' => 'مبقع', 'hi' => 'धब्बेदार', 'it' => 'Macchiato', 'zh' => '斑点状', 'tr' => 'Benekli']],
                ],
                'unit'                 => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 11,
            ],

            // ── 12. Water Absorption ────────────────────────────────
            [
                'key'   => 'water_absorption',
                'type'  => 'number',
                'label' => [
                    'fa' => 'میزان جذب آب',
                    'en' => 'Water Absorption',
                    'ar' => 'امتصاص الماء',
                    'hi' => 'जल अवशोषण',
                    'it' => 'Assorbimento d\'Acqua',
                    'zh' => '吸水率',
                    'tr' => 'Su Emme',
                ],
                'group' => [
                    'fa' => 'مشخصات فنی',
                    'en' => 'Technical Specifications',
                    'ar' => 'المواصفات التقنية',
                    'hi' => 'तकनीकी विशिष्टताएं',
                    'it' => 'Specifiche Tecniche',
                    'zh' => '技术规格',
                    'tr' => 'Teknik Özellikler',
                ],
                'unit'                 => '%',
                'min_value'            => 0,
                'max_value'            => 100,
                'step_value'           => 0.01,
                'default_value'        => null,
                'is_filterable'        => false,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 12,
            ],

            // ── 13. Compressive Strength ─────────────────────────────
            [
                'key'   => 'compressive_strength',
                'type'  => 'number',
                'label' => [
                    'fa' => 'مقاومت فشاری',
                    'en' => 'Compressive Strength',
                    'ar' => 'قوة الضغط',
                    'hi' => 'संपीड़न शक्ति',
                    'it' => 'Resistenza alla Compressione',
                    'zh' => '抗压强度',
                    'tr' => 'Basınç Dayanımı',
                ],
                'group' => [
                    'fa' => 'مشخصات فنی',
                    'en' => 'Technical Specifications',
                    'ar' => 'المواصفات التقنية',
                    'hi' => 'तकनीकी विशिष्टताएं',
                    'it' => 'Specifiche Tecniche',
                    'zh' => '技术规格',
                    'tr' => 'Teknik Özellikler',
                ],
                'unit'                 => 'MPa',
                'min_value'            => 0,
                'max_value'            => null,
                'step_value'           => 0.1,
                'default_value'        => null,
                'is_filterable'        => false,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 13,
            ],

            // ── 14. Density ───────────────────────────────────────
            [
                'key'   => 'density',
                'type'  => 'number',
                'label' => [
                    'fa' => 'چگالی',
                    'en' => 'Density',
                    'ar' => 'الكثافة',
                    'hi' => 'घनत्व',
                    'it' => 'Densità',
                    'zh' => '密度',
                    'tr' => 'Yoğunluk',
                ],
                'group' => [
                    'fa' => 'مشخصات فنی',
                    'en' => 'Technical Specifications',
                    'ar' => 'المواصفات التقنية',
                    'hi' => 'तकनीकी विशिष्टताएं',
                    'it' => 'Specifiche Tecniche',
                    'zh' => '技术规格',
                    'tr' => 'Teknik Özellikler',
                ],
                'unit'                 => 'g/cm3',
                'min_value'            => 0,
                'max_value'            => null,
                'step_value'           => 0.01,
                'default_value'        => null,
                'is_filterable'        => false,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 14,
            ],

            // ── 15. Frost Resistant ───────────────────────────────
            [
                'key'   => 'frost_resistant',
                'type'  => 'bool',
                'label' => [
                    'fa' => 'مقاوم در برابر یخ‌زدگی',
                    'en' => 'Frost Resistant',
                    'ar' => 'مقاوم للصقيع',
                    'hi' => 'ठंढ प्रतिरोधी',
                    'it' => 'Resistente al Gelo',
                    'zh' => '抗冻性',
                    'tr' => 'Dona Dayanıklı',
                ],
                'group' => [
                    'fa' => 'مشخصات فنی',
                    'en' => 'Technical Specifications',
                    'ar' => 'المواصفات التقنية',
                    'hi' => 'तकनीकी विशिष्टताएं',
                    'it' => 'Specifiche Tecniche',
                    'zh' => '技术规格',
                    'tr' => 'Teknik Özellikler',
                ],
                'unit'                 => null,
                'default_value'        => '0',
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 15,
            ],

            // ── 16. Suitable Usage ────────────────────────────────
            [
                'key'   => 'usage',
                'type'  => 'select',
                'label' => [
                    'fa' => 'کاربری مناسب',
                    'en' => 'Suitable Usage',
                    'ar' => 'الاستخدام المناسب',
                    'hi' => 'उपयुक्त उपयोग',
                    'it' => 'Utilizzo Consigliato',
                    'zh' => '适用用途',
                    'tr' => 'Uygun Kullanım',
                ],
                'group' => [
                    'fa' => 'کاربری',
                    'en' => 'Application',
                    'ar' => 'التطبيق',
                    'hi' => 'अनुप्रयोग',
                    'it' => 'Applicazione',
                    'zh' => '应用',
                    'tr' => 'Uygulama',
                ],
                'options' => [
                    ['key' => 'flooring',     'label' => ['fa' => 'کف‌پوش', 'en' => 'Flooring', 'ar' => 'أرضيات', 'hi' => 'फ़्लोरिंग', 'it' => 'Pavimentazione', 'zh' => '地面铺装', 'tr' => 'Zemin Döşeme']],
                    ['key' => 'wall_cladding','label' => ['fa' => 'نمای دیوار', 'en' => 'Wall Cladding', 'ar' => 'تكسية الجدران', 'hi' => 'दीवार आवरण', 'it' => 'Rivestimento Murale', 'zh' => '墙面装饰', 'tr' => 'Duvar Kaplama']],
                    ['key' => 'facade',       'label' => ['fa' => 'نمای ساختمان', 'en' => 'Facade', 'ar' => 'واجهة', 'hi' => 'फ़साड', 'it' => 'Facciata', 'zh' => '外墙', 'tr' => 'Cephe']],
                    ['key' => 'countertop',   'label' => ['fa' => 'صفحه کابینت', 'en' => 'Countertop', 'ar' => 'سطح العمل', 'hi' => 'काउंटरटॉप', 'it' => 'Piano di Lavoro', 'zh' => '台面', 'tr' => 'Tezgah']],
                    ['key' => 'staircase',    'label' => ['fa' => 'پله', 'en' => 'Staircase', 'ar' => 'درج', 'hi' => 'सीढ़ी', 'it' => 'Scala', 'zh' => '楼梯', 'tr' => 'Merdiven']],
                    ['key' => 'landscape',    'label' => ['fa' => 'محوطه‌سازی', 'en' => 'Landscape', 'ar' => 'تنسيق الحدائق', 'hi' => 'भूदृश्य', 'it' => 'Paesaggistica', 'zh' => '园林景观', 'tr' => 'Peyzaj']],
                    ['key' => 'pool',         'label' => ['fa' => 'استخر', 'en' => 'Pool', 'ar' => 'حمام سباحة', 'hi' => 'पूल', 'it' => 'Piscina', 'zh' => '泳池', 'tr' => 'Havuz']],
                ],
                'unit'                 => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 16,
            ],

            // ── 17. Indoor / Outdoor Use ────────────────────────────
            [
                'key'   => 'usage_environment',
                'type'  => 'select',
                'label' => [
                    'fa' => 'محل کاربری',
                    'en' => 'Indoor / Outdoor',
                    'ar' => 'داخلي / خارجي',
                    'hi' => 'इनडोर / आउटडोर',
                    'it' => 'Interno / Esterno',
                    'zh' => '室内/室外',
                    'tr' => 'İç Mekan / Dış Mekan',
                ],
                'group' => [
                    'fa' => 'کاربری',
                    'en' => 'Application',
                    'ar' => 'التطبيق',
                    'hi' => 'अनुप्रयोग',
                    'it' => 'Applicazione',
                    'zh' => '应用',
                    'tr' => 'Uygulama',
                ],
                'options' => [
                    ['key' => 'indoor',  'label' => ['fa' => 'داخلی',  'en' => 'Indoor',  'ar' => 'داخلي',  'hi' => 'इनडोर',  'it' => 'Interno', 'zh' => '室内', 'tr' => 'İç Mekan']],
                    ['key' => 'outdoor', 'label' => ['fa' => 'خارجی',  'en' => 'Outdoor', 'ar' => 'خارجي',  'hi' => 'आउटडोर', 'it' => 'Esterno', 'zh' => '室外', 'tr' => 'Dış Mekan']],
                    ['key' => 'both',    'label' => ['fa' => 'هر دو',  'en' => 'Both',    'ar' => 'كلاهما', 'hi' => 'दोनों',  'it' => 'Entrambi', 'zh' => '两者皆可', 'tr' => 'Her İkisi']],
                ],
                'unit'                 => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 17,
            ],

            // ── 18. Slip Resistance ───────────────────────────────
            [
                'key'   => 'slip_resistance',
                'type'  => 'select',
                'label' => [
                    'fa' => 'مقاومت در برابر لغزش',
                    'en' => 'Slip Resistance',
                    'ar' => 'مقاومة الانزلاق',
                    'hi' => 'फिसलन प्रतिरोध',
                    'it' => 'Resistenza allo Scivolamento',
                    'zh' => '防滑性',
                    'tr' => 'Kayma Direnci',
                ],
                'group' => [
                    'fa' => 'مشخصات فنی',
                    'en' => 'Technical Specifications',
                    'ar' => 'المواصفات التقنية',
                    'hi' => 'तकनीकी विशिष्टताएं',
                    'it' => 'Specifiche Tecniche',
                    'zh' => '技术规格',
                    'tr' => 'Teknik Özellikler',
                ],
                'options' => [
                    ['key' => 'low',    'label' => ['fa' => 'کم',    'en' => 'Low',    'ar' => 'منخفض', 'hi' => 'कम',    'it' => 'Bassa', 'zh' => '低', 'tr' => 'Düşük']],
                    ['key' => 'medium', 'label' => ['fa' => 'متوسط', 'en' => 'Medium', 'ar' => 'متوسط', 'hi' => 'मध्यम', 'it' => 'Media', 'zh' => '中', 'tr' => 'Orta']],
                    ['key' => 'high',   'label' => ['fa' => 'بالا',  'en' => 'High',   'ar' => 'عالي',  'hi' => 'उच्च',  'it' => 'Alta', 'zh' => '高', 'tr' => 'Yüksek']],
                ],
                'unit'                 => null,
                'is_filterable'        => true,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 18,
            ],

            // ── 19. Edge Profile ──────────────────────────────────
            [
                'key'   => 'edge_profile',
                'type'  => 'select',
                'label' => [
                    'fa' => 'پروفیل لبه',
                    'en' => 'Edge Profile',
                    'ar' => 'شكل الحافة',
                    'hi' => 'एज प्रोफ़ाइल',
                    'it' => 'Profilo del Bordo',
                    'zh' => '边缘造型',
                    'tr' => 'Kenar Profili',
                ],
                'group' => [
                    'fa' => 'مشخصات فنی',
                    'en' => 'Technical Specifications',
                    'ar' => 'المواصفات التقنية',
                    'hi' => 'तकनीकी विशिष्टताएं',
                    'it' => 'Specifiche Tecniche',
                    'zh' => '技术规格',
                    'tr' => 'Teknik Özellikler',
                ],
                'options' => [
                    ['key' => 'straight', 'label' => ['fa' => 'صاف', 'en' => 'Straight', 'ar' => 'مستقيم', 'hi' => 'सीधा', 'it' => 'Dritto', 'zh' => '直边', 'tr' => 'Düz']],
                    ['key' => 'bullnose', 'label' => ['fa' => 'گرد (بول‌نوز)', 'en' => 'Bullnose', 'ar' => 'مستدير', 'hi' => 'बुलनोज़', 'it' => 'Bullnose', 'zh' => '圆边', 'tr' => 'Yuvarlak Kenar']],
                    ['key' => 'beveled',  'label' => ['fa' => 'پخ‌دار', 'en' => 'Beveled', 'ar' => 'مشطوف', 'hi' => 'बेवल्ड', 'it' => 'Smussato', 'zh' => '斜边', 'tr' => 'Pahlı']],
                    ['key' => 'chiseled', 'label' => ['fa' => 'تراش‌خورده', 'en' => 'Chiseled', 'ar' => 'منحوت', 'hi' => 'छेनी से तराशा', 'it' => 'Scalpellato', 'zh' => '凿边', 'tr' => 'Yontulmuş']],
                ],
                'unit'                 => null,
                'is_filterable'        => false,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 19,
            ],

            // ── 20. Packaging Type ────────────────────────────────
            [
                'key'   => 'packaging_type',
                'type'  => 'select',
                'label' => [
                    'fa' => 'نوع بسته‌بندی',
                    'en' => 'Packaging Type',
                    'ar' => 'نوع التعبئة',
                    'hi' => 'पैकेजिंग प्रकार',
                    'it' => 'Tipo di Imballaggio',
                    'zh' => '包装类型',
                    'tr' => 'Ambalaj Türü',
                ],
                'group' => [
                    'fa' => 'بسته‌بندی و حمل',
                    'en' => 'Packaging & Shipping',
                    'ar' => 'التعبئة والشحن',
                    'hi' => 'पैकेजिंग और शिपिंग',
                    'it' => 'Imballaggio e Spedizione',
                    'zh' => '包装与运输',
                    'tr' => 'Ambalaj ve Sevkiyat',
                ],
                'options' => [
                    ['key' => 'wooden_crate', 'label' => ['fa' => 'باکس چوبی', 'en' => 'Wooden Crate', 'ar' => 'صندوق خشبي', 'hi' => 'लकड़ी का बक्सा', 'it' => 'Cassa di Legno', 'zh' => '木箱', 'tr' => 'Ahşap Sandık']],
                    ['key' => 'bundle',       'label' => ['fa' => 'بسته (باندل)', 'en' => 'Bundle', 'ar' => 'حزمة', 'hi' => 'बंडल', 'it' => 'Fascio', 'zh' => '捆包', 'tr' => 'Demet']],
                    ['key' => 'pallet',       'label' => ['fa' => 'پالت', 'en' => 'Pallet', 'ar' => 'منصة نقالة', 'hi' => 'पैलेट', 'it' => 'Pallet', 'zh' => '托盘', 'tr' => 'Palet']],
                    ['key' => 'loose',        'label' => ['fa' => 'فاقد بسته‌بندی', 'en' => 'Loose', 'ar' => 'سائب', 'hi' => 'खुला', 'it' => 'Sfuso', 'zh' => '散装', 'tr' => 'Dökme']],
                ],
                'unit'                 => null,
                'is_filterable'        => false,
                'show_in_product_page' => true,
                'show_in_card'         => false,
                'is_active'            => true,
                'sort_order'           => 20,
            ],

        ];

        foreach ($attributes as $attr) {
            Attribute::updateOrCreate(
                ['key' => $attr['key']],
                $attr
            );
        }

        $this->command->info(count($attributes) . ' attributes seeded successfully.');
    }
}
