<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): coupons
 * Generated at: 2026-07-11 08:54:15
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class CouponSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('coupons')->delete();


    }
}
