<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): languages
 * Generated at: 2026-07-11 08:54:14
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class LanguageSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('languages')->delete();


        DB::table('languages')->insert([
            [
                'id' => 1,
                'name' => 'Persian',
                'native_name' => 'فارسی',
                'code' => 'fa',
                'locale' => 'fa_IR',
                'direction' => 'rtl',
                'flag' => '🇮🇷',
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 0,
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 2,
                'name' => 'English',
                'native_name' => 'English',
                'code' => 'en',
                'locale' => 'en_US',
                'direction' => 'ltr',
                'flag' => '🇬🇧',
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 3,
                'name' => 'Hindi',
                'native_name' => 'हिन्दी',
                'code' => 'hi',
                'locale' => 'hi_IN',
                'direction' => 'ltr',
                'flag' => '🇮🇳',
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 4,
                'name' => 'Italian',
                'native_name' => 'Italiano',
                'code' => 'it',
                'locale' => 'it_IT',
                'direction' => 'ltr',
                'flag' => '🇮🇹',
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 5,
                'name' => 'Arabic',
                'native_name' => 'العربية',
                'code' => 'ar',
                'locale' => 'ar_SA',
                'direction' => 'rtl',
                'flag' => '🇸🇦',
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 6,
                'name' => 'Chinese',
                'native_name' => '中文',
                'code' => 'zh',
                'locale' => 'zh_CN',
                'direction' => 'ltr',
                'flag' => '🇨🇳',
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 7,
                'name' => 'Turkish',
                'native_name' => 'Türkçe',
                'code' => 'tr',
                'locale' => 'tr_TR',
                'direction' => 'ltr',
                'flag' => '🇹🇷',
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ]
        ]);

    }
}
