<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): menus
 * Generated at: 2026-07-11 08:54:15
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class MenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menus')->delete();


        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => 'منوی اصلی',
                'location' => 'header',
                'is_active' => 1,
                'created_at' => '2026-07-10 18:00:50',
                'updated_at' => '2026-07-10 18:00:50'
            ],
            [
                'id' => 2,
                'name' => 'منوی فوتر',
                'location' => 'footer',
                'is_active' => 1,
                'created_at' => '2026-07-10 18:00:50',
                'updated_at' => '2026-07-10 18:00:50'
            ]
        ]);

    }
}
