<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): orders
 * Generated at: 2026-07-11 09:27:43
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class OrderSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('orders')->delete();


    }
}
