<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): product_attributes
 * Generated at: 2026-07-11 08:54:14
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class ProductAttributeSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('product_attributes')->delete();


        DB::table('product_attributes')->insert([
            [
                'id' => 1,
                'product_id' => 1,
                'attribute_id' => 1,
                'value' => '{"en": "Red", "fa": "قرمز"}',
                'sort_order' => 0,
                'created_at' => '2026-07-10 17:13:46',
                'updated_at' => '2026-07-10 17:13:46'
            ],
            [
                'id' => 2,
                'product_id' => 1,
                'attribute_id' => 2,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 17:13:46',
                'updated_at' => '2026-07-10 17:13:46'
            ],
            [
                'id' => 3,
                'product_id' => 2,
                'attribute_id' => 3,
                'value' => '{"en": "Red", "fa": "قرمز"}',
                'sort_order' => 0,
                'created_at' => '2026-07-10 17:13:47',
                'updated_at' => '2026-07-10 17:13:47'
            ],
            [
                'id' => 4,
                'product_id' => 2,
                'attribute_id' => 4,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 17:13:47',
                'updated_at' => '2026-07-10 17:13:47'
            ],
            [
                'id' => 5,
                'product_id' => 3,
                'attribute_id' => 5,
                'value' => '{"en": "Red", "fa": "قرمز"}',
                'sort_order' => 0,
                'created_at' => '2026-07-10 17:13:47',
                'updated_at' => '2026-07-10 17:13:47'
            ],
            [
                'id' => 6,
                'product_id' => 3,
                'attribute_id' => 6,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 17:13:47',
                'updated_at' => '2026-07-10 17:13:47'
            ],
            [
                'id' => 7,
                'product_id' => 4,
                'attribute_id' => 7,
                'value' => '{"en": "Red", "fa": "قرمز"}',
                'sort_order' => 0,
                'created_at' => '2026-07-10 17:13:48',
                'updated_at' => '2026-07-10 17:13:48'
            ],
            [
                'id' => 8,
                'product_id' => 4,
                'attribute_id' => 8,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 17:13:48',
                'updated_at' => '2026-07-10 17:13:48'
            ],
            [
                'id' => 9,
                'product_id' => 5,
                'attribute_id' => 9,
                'value' => '{"value": "gray"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:01:18',
                'updated_at' => '2026-07-10 18:01:18'
            ],
            [
                'id' => 10,
                'product_id' => 5,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:01:18',
                'updated_at' => '2026-07-10 18:01:18'
            ],
            [
                'id' => 11,
                'product_id' => 5,
                'attribute_id' => 11,
                'value' => '{"value": 320}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:01:18',
                'updated_at' => '2026-07-10 18:01:18'
            ],
            [
                'id' => 12,
                'product_id' => 5,
                'attribute_id' => 12,
                'value' => '{"value": 190}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:01:18',
                'updated_at' => '2026-07-10 18:01:18'
            ],
            [
                'id' => 13,
                'product_id' => 5,
                'attribute_id' => 13,
                'value' => '{"value": 175}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:01:18',
                'updated_at' => '2026-07-10 18:01:18'
            ],
            [
                'id' => 14,
                'product_id' => 5,
                'attribute_id' => 15,
                'value' => '{"value": 10.64}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 15,
                'product_id' => 5,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر آتشكوه، محلات", "en": "Atashkuh Mine, Mahallat", "fa": "معدن آتشکوه، محلات", "hi": "आतशकूह खदान, महल्लात", "it": "Miniera di Atashkuh, Mahallat", "tr": "Atashkuh Madeni, Mahallat", "zh": "阿塔什库矿, 马哈拉特"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 16,
                'product_id' => 5,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 17,
                'product_id' => 5,
                'attribute_id' => 18,
                'value' => '{"value": "premium"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 18,
                'product_id' => 5,
                'attribute_id' => 19,
                'value' => '{"value": "veined"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 19,
                'product_id' => 5,
                'attribute_id' => 20,
                'value' => '{"value": 2.1}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 20,
                'product_id' => 5,
                'attribute_id' => 21,
                'value' => '{"value": 75}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 21,
                'product_id' => 5,
                'attribute_id' => 22,
                'value' => '{"value": 2.4}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 22,
                'product_id' => 5,
                'attribute_id' => 23,
                'value' => '{"value": true}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 23,
                'product_id' => 5,
                'attribute_id' => 24,
                'value' => '{"value": "flooring"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 24,
                'product_id' => 5,
                'attribute_id' => 25,
                'value' => '{"value": "both"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 25,
                'product_id' => 5,
                'attribute_id' => 26,
                'value' => '{"value": "medium"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 26,
                'product_id' => 5,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 27,
                'product_id' => 5,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:01:19',
                'updated_at' => '2026-07-10 18:01:19'
            ],
            [
                'id' => 28,
                'product_id' => 6,
                'attribute_id' => 9,
                'value' => '{"value": "gray"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 29,
                'product_id' => 6,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 30,
                'product_id' => 6,
                'attribute_id' => 11,
                'value' => '{"value": 300}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 31,
                'product_id' => 6,
                'attribute_id' => 12,
                'value' => '{"value": 170}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 32,
                'product_id' => 6,
                'attribute_id' => 13,
                'value' => '{"value": 198}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 33,
                'product_id' => 6,
                'attribute_id' => 15,
                'value' => '{"value": 10.1}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 34,
                'product_id' => 6,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر هرسين", "en": "Harsin Mine", "fa": "معدن هرسین", "hi": "हरसिन खदान", "it": "Miniera di Harsin", "tr": "Harsin Madeni", "zh": "哈尔辛矿"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 35,
                'product_id' => 6,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 36,
                'product_id' => 6,
                'attribute_id' => 18,
                'value' => '{"value": "standard"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 37,
                'product_id' => 6,
                'attribute_id' => 19,
                'value' => '{"value": "veined"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 38,
                'product_id' => 6,
                'attribute_id' => 20,
                'value' => '{"value": 2.4}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 39,
                'product_id' => 6,
                'attribute_id' => 21,
                'value' => '{"value": 70}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 40,
                'product_id' => 6,
                'attribute_id' => 22,
                'value' => '{"value": 2.37}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 41,
                'product_id' => 6,
                'attribute_id' => 23,
                'value' => '{"value": true}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 42,
                'product_id' => 6,
                'attribute_id' => 24,
                'value' => '{"value": "wall_cladding"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 43,
                'product_id' => 6,
                'attribute_id' => 25,
                'value' => '{"value": "both"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 44,
                'product_id' => 6,
                'attribute_id' => 26,
                'value' => '{"value": "medium"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 45,
                'product_id' => 6,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 46,
                'product_id' => 6,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:01:24',
                'updated_at' => '2026-07-10 18:01:24'
            ],
            [
                'id' => 47,
                'product_id' => 7,
                'attribute_id' => 9,
                'value' => '{"value": "gray"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 48,
                'product_id' => 7,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 49,
                'product_id' => 7,
                'attribute_id' => 11,
                'value' => '{"value": 320}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 50,
                'product_id' => 7,
                'attribute_id' => 12,
                'value' => '{"value": 190}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 51,
                'product_id' => 7,
                'attribute_id' => 13,
                'value' => '{"value": 200}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 52,
                'product_id' => 7,
                'attribute_id' => 15,
                'value' => '{"value": 12.16}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 53,
                'product_id' => 7,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر آتشكوه، محلات", "en": "Atashkuh Mine, Mahallat", "fa": "معدن آتشکوه، محلات", "hi": "आतशकूह खदान, महल्लात", "it": "Miniera di Atashkuh, Mahallat", "tr": "Atashkuh Madeni, Mahallat", "zh": "阿塔什库矿, 马哈拉特"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 54,
                'product_id' => 7,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 55,
                'product_id' => 7,
                'attribute_id' => 18,
                'value' => '{"value": "premium"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 56,
                'product_id' => 7,
                'attribute_id' => 19,
                'value' => '{"value": "veined"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 57,
                'product_id' => 7,
                'attribute_id' => 20,
                'value' => '{"value": 2}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 58,
                'product_id' => 7,
                'attribute_id' => 21,
                'value' => '{"value": 77}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 59,
                'product_id' => 7,
                'attribute_id' => 22,
                'value' => '{"value": 2.41}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 60,
                'product_id' => 7,
                'attribute_id' => 23,
                'value' => '{"value": true}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 61,
                'product_id' => 7,
                'attribute_id' => 24,
                'value' => '{"value": "facade"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 62,
                'product_id' => 7,
                'attribute_id' => 25,
                'value' => '{"value": "both"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 63,
                'product_id' => 7,
                'attribute_id' => 26,
                'value' => '{"value": "medium"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 64,
                'product_id' => 7,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 65,
                'product_id' => 7,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:01:33',
                'updated_at' => '2026-07-10 18:01:33'
            ],
            [
                'id' => 66,
                'product_id' => 8,
                'attribute_id' => 9,
                'value' => '{"value": "gray"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 67,
                'product_id' => 8,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 68,
                'product_id' => 8,
                'attribute_id' => 11,
                'value' => '{"value": 290}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 69,
                'product_id' => 8,
                'attribute_id' => 12,
                'value' => '{"value": 180}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 70,
                'product_id' => 8,
                'attribute_id' => 13,
                'value' => '{"value": 170}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 71,
                'product_id' => 8,
                'attribute_id' => 15,
                'value' => '{"value": 8.88}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 72,
                'product_id' => 8,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر آتشكوه، محلات", "en": "Atashkuh Mine, Mahallat", "fa": "معدن آتشکوه، محلات", "hi": "आतशकूह खदान, महल्लात", "it": "Miniera di Atashkuh, Mahallat", "tr": "Atashkuh Madeni, Mahallat", "zh": "阿塔什库矿, 马哈拉特"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 73,
                'product_id' => 8,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 74,
                'product_id' => 8,
                'attribute_id' => 18,
                'value' => '{"value": "standard"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 75,
                'product_id' => 8,
                'attribute_id' => 19,
                'value' => '{"value": "veined"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 76,
                'product_id' => 8,
                'attribute_id' => 20,
                'value' => '{"value": 2.3}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 77,
                'product_id' => 8,
                'attribute_id' => 21,
                'value' => '{"value": 71}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 78,
                'product_id' => 8,
                'attribute_id' => 22,
                'value' => '{"value": 2.38}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 79,
                'product_id' => 8,
                'attribute_id' => 23,
                'value' => '{"value": true}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 80,
                'product_id' => 8,
                'attribute_id' => 24,
                'value' => '{"value": "wall_cladding"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:01:35',
                'updated_at' => '2026-07-10 18:01:35'
            ],
            [
                'id' => 81,
                'product_id' => 8,
                'attribute_id' => 25,
                'value' => '{"value": "indoor"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:01:36',
                'updated_at' => '2026-07-10 18:01:36'
            ],
            [
                'id' => 82,
                'product_id' => 8,
                'attribute_id' => 26,
                'value' => '{"value": "medium"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:01:36',
                'updated_at' => '2026-07-10 18:01:36'
            ],
            [
                'id' => 83,
                'product_id' => 8,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:01:36',
                'updated_at' => '2026-07-10 18:01:36'
            ],
            [
                'id' => 84,
                'product_id' => 8,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:01:36',
                'updated_at' => '2026-07-10 18:01:36'
            ],
            [
                'id' => 85,
                'product_id' => 9,
                'attribute_id' => 9,
                'value' => '{"value": "cream"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 86,
                'product_id' => 9,
                'attribute_id' => 10,
                'value' => '{"value": "honed"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 87,
                'product_id' => 9,
                'attribute_id' => 11,
                'value' => '{"value": 280}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 88,
                'product_id' => 9,
                'attribute_id' => 12,
                'value' => '{"value": 170}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 89,
                'product_id' => 9,
                'attribute_id' => 13,
                'value' => '{"value": 165}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 90,
                'product_id' => 9,
                'attribute_id' => 15,
                'value' => '{"value": 7.85}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 91,
                'product_id' => 9,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر محلات", "en": "Mahallat Mine", "fa": "معدن محلات", "hi": "महल्लात खदान", "it": "Miniera di Mahallat", "tr": "Mahallat Madeni", "zh": "马哈拉特矿"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 92,
                'product_id' => 9,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 93,
                'product_id' => 9,
                'attribute_id' => 18,
                'value' => '{"value": "premium"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 94,
                'product_id' => 9,
                'attribute_id' => 19,
                'value' => '{"value": "uniform"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 95,
                'product_id' => 9,
                'attribute_id' => 20,
                'value' => '{"value": 1.7}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 96,
                'product_id' => 9,
                'attribute_id' => 21,
                'value' => '{"value": 82}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 97,
                'product_id' => 9,
                'attribute_id' => 22,
                'value' => '{"value": 2.46}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 98,
                'product_id' => 9,
                'attribute_id' => 23,
                'value' => '{"value": true}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 99,
                'product_id' => 9,
                'attribute_id' => 24,
                'value' => '{"value": "flooring"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 100,
                'product_id' => 9,
                'attribute_id' => 25,
                'value' => '{"value": "indoor"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 101,
                'product_id' => 9,
                'attribute_id' => 26,
                'value' => '{"value": "medium"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 102,
                'product_id' => 9,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 103,
                'product_id' => 9,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:01:38',
                'updated_at' => '2026-07-10 18:01:38'
            ],
            [
                'id' => 104,
                'product_id' => 10,
                'attribute_id' => 9,
                'value' => '{"value": "brown"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 105,
                'product_id' => 10,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 106,
                'product_id' => 10,
                'attribute_id' => 11,
                'value' => '{"value": 280}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 107,
                'product_id' => 10,
                'attribute_id' => 12,
                'value' => '{"value": 175}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 108,
                'product_id' => 10,
                'attribute_id' => 13,
                'value' => '{"value": 160}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 109,
                'product_id' => 10,
                'attribute_id' => 15,
                'value' => '{"value": 7.84}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 110,
                'product_id' => 10,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر عباس آباد", "en": "Abbasabad Mine", "fa": "معدن عباس‌آباد", "hi": "अब्बासाबाद खदान", "it": "Miniera di Abbasabad", "tr": "Abbasabad Madeni", "zh": "阿巴萨巴德矿"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 111,
                'product_id' => 10,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 112,
                'product_id' => 10,
                'attribute_id' => 18,
                'value' => '{"value": "premium"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 113,
                'product_id' => 10,
                'attribute_id' => 19,
                'value' => '{"value": "veined"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 114,
                'product_id' => 10,
                'attribute_id' => 20,
                'value' => '{"value": 2.5}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 115,
                'product_id' => 10,
                'attribute_id' => 21,
                'value' => '{"value": 68}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 116,
                'product_id' => 10,
                'attribute_id' => 22,
                'value' => '{"value": 2.35}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 117,
                'product_id' => 10,
                'attribute_id' => 23,
                'value' => '{"value": false}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 118,
                'product_id' => 10,
                'attribute_id' => 24,
                'value' => '{"value": "wall_cladding"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 119,
                'product_id' => 10,
                'attribute_id' => 25,
                'value' => '{"value": "indoor"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 120,
                'product_id' => 10,
                'attribute_id' => 26,
                'value' => '{"value": "low"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 121,
                'product_id' => 10,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 122,
                'product_id' => 10,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:01:47',
                'updated_at' => '2026-07-10 18:01:47'
            ],
            [
                'id' => 123,
                'product_id' => 11,
                'attribute_id' => 9,
                'value' => '{"value": "brown"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 124,
                'product_id' => 11,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 125,
                'product_id' => 11,
                'attribute_id' => 11,
                'value' => '{"value": 310}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 126,
                'product_id' => 11,
                'attribute_id' => 12,
                'value' => '{"value": 175}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 127,
                'product_id' => 11,
                'attribute_id' => 13,
                'value' => '{"value": 190}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 128,
                'product_id' => 11,
                'attribute_id' => 15,
                'value' => '{"value": 10.31}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 129,
                'product_id' => 11,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر عباس آباد", "en": "Abbasabad Mine", "fa": "معدن عباس‌آباد", "hi": "अब्बासाबाद खदान", "it": "Miniera di Abbasabad", "tr": "Abbasabad Madeni", "zh": "阿巴萨巴德矿"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 130,
                'product_id' => 11,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 131,
                'product_id' => 11,
                'attribute_id' => 18,
                'value' => '{"value": "premium"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 132,
                'product_id' => 11,
                'attribute_id' => 19,
                'value' => '{"value": "veined"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 133,
                'product_id' => 11,
                'attribute_id' => 20,
                'value' => '{"value": 2.4}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 134,
                'product_id' => 11,
                'attribute_id' => 21,
                'value' => '{"value": 70}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 135,
                'product_id' => 11,
                'attribute_id' => 22,
                'value' => '{"value": 2.36}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 136,
                'product_id' => 11,
                'attribute_id' => 23,
                'value' => '{"value": false}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 137,
                'product_id' => 11,
                'attribute_id' => 24,
                'value' => '{"value": "facade"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 138,
                'product_id' => 11,
                'attribute_id' => 25,
                'value' => '{"value": "both"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 139,
                'product_id' => 11,
                'attribute_id' => 26,
                'value' => '{"value": "medium"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 140,
                'product_id' => 11,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 141,
                'product_id' => 11,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:01:56',
                'updated_at' => '2026-07-10 18:01:56'
            ],
            [
                'id' => 142,
                'product_id' => 12,
                'attribute_id' => 9,
                'value' => '{"value": "brown"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 143,
                'product_id' => 12,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 144,
                'product_id' => 12,
                'attribute_id' => 11,
                'value' => '{"value": 270}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 145,
                'product_id' => 12,
                'attribute_id' => 12,
                'value' => '{"value": 180}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 146,
                'product_id' => 12,
                'attribute_id' => 13,
                'value' => '{"value": 185}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 147,
                'product_id' => 12,
                'attribute_id' => 15,
                'value' => '{"value": 8.99}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 148,
                'product_id' => 12,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر عباس آباد", "en": "Abbasabad Mine", "fa": "معدن عباس‌آباد", "hi": "अब्बासाबाद खदान", "it": "Miniera di Abbasabad", "tr": "Abbasabad Madeni", "zh": "阿巴萨巴德矿"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 149,
                'product_id' => 12,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 150,
                'product_id' => 12,
                'attribute_id' => 18,
                'value' => '{"value": "standard"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 151,
                'product_id' => 12,
                'attribute_id' => 19,
                'value' => '{"value": "veined"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 152,
                'product_id' => 12,
                'attribute_id' => 20,
                'value' => '{"value": 2.6}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 153,
                'product_id' => 12,
                'attribute_id' => 21,
                'value' => '{"value": 66}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 154,
                'product_id' => 12,
                'attribute_id' => 22,
                'value' => '{"value": 2.33}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 155,
                'product_id' => 12,
                'attribute_id' => 23,
                'value' => '{"value": false}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 156,
                'product_id' => 12,
                'attribute_id' => 24,
                'value' => '{"value": "landscape"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 157,
                'product_id' => 12,
                'attribute_id' => 25,
                'value' => '{"value": "outdoor"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 158,
                'product_id' => 12,
                'attribute_id' => 26,
                'value' => '{"value": "medium"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 159,
                'product_id' => 12,
                'attribute_id' => 27,
                'value' => '{"value": "chiseled"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 160,
                'product_id' => 12,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:02:06',
                'updated_at' => '2026-07-10 18:02:06'
            ],
            [
                'id' => 161,
                'product_id' => 13,
                'attribute_id' => 9,
                'value' => '{"value": "honey"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 162,
                'product_id' => 13,
                'attribute_id' => 10,
                'value' => '{"value": "natural_split"}',
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 163,
                'product_id' => 13,
                'attribute_id' => 11,
                'value' => '{"value": 300}',
                'sort_order' => 3,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 164,
                'product_id' => 13,
                'attribute_id' => 12,
                'value' => '{"value": 155}',
                'sort_order' => 4,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 165,
                'product_id' => 13,
                'attribute_id' => 13,
                'value' => '{"value": 170}',
                'sort_order' => 5,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 166,
                'product_id' => 13,
                'attribute_id' => 15,
                'value' => '{"value": 7.91}',
                'sort_order' => 6,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 167,
                'product_id' => 13,
                'attribute_id' => 16,
                'value' => '{"ar": "محجر عباس آباد", "en": "Abbasabad Mine", "fa": "معدن عباس‌آباد", "hi": "अब्बासाबाद खदान", "it": "Miniera di Abbasabad", "tr": "Abbasabad Madeni", "zh": "阿巴萨巴德矿"}',
                'sort_order' => 7,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 168,
                'product_id' => 13,
                'attribute_id' => 17,
                'value' => '"Iran"',
                'sort_order' => 8,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 169,
                'product_id' => 13,
                'attribute_id' => 18,
                'value' => '{"value": "standard"}',
                'sort_order' => 9,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 170,
                'product_id' => 13,
                'attribute_id' => 19,
                'value' => '{"value": "uniform"}',
                'sort_order' => 10,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 171,
                'product_id' => 13,
                'attribute_id' => 20,
                'value' => '{"value": 2.7}',
                'sort_order' => 11,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 172,
                'product_id' => 13,
                'attribute_id' => 21,
                'value' => '{"value": 64}',
                'sort_order' => 12,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 173,
                'product_id' => 13,
                'attribute_id' => 22,
                'value' => '{"value": 2.32}',
                'sort_order' => 13,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 174,
                'product_id' => 13,
                'attribute_id' => 23,
                'value' => '{"value": false}',
                'sort_order' => 14,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 175,
                'product_id' => 13,
                'attribute_id' => 24,
                'value' => '{"value": "flooring"}',
                'sort_order' => 15,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 176,
                'product_id' => 13,
                'attribute_id' => 25,
                'value' => '{"value": "indoor"}',
                'sort_order' => 16,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 177,
                'product_id' => 13,
                'attribute_id' => 26,
                'value' => '{"value": "low"}',
                'sort_order' => 17,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 178,
                'product_id' => 13,
                'attribute_id' => 27,
                'value' => '{"value": "straight"}',
                'sort_order' => 18,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 179,
                'product_id' => 13,
                'attribute_id' => 28,
                'value' => '{"value": "loose"}',
                'sort_order' => 19,
                'created_at' => '2026-07-10 18:02:16',
                'updated_at' => '2026-07-10 18:02:16'
            ],
            [
                'id' => 180,
                'product_id' => 14,
                'attribute_id' => 29,
                'value' => '{"en": "Red", "fa": "قرمز"}',
                'sort_order' => 0,
                'created_at' => '2026-07-10 18:52:54',
                'updated_at' => '2026-07-10 18:52:54'
            ],
            [
                'id' => 181,
                'product_id' => 14,
                'attribute_id' => 30,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:52:54',
                'updated_at' => '2026-07-10 18:52:54'
            ],
            [
                'id' => 182,
                'product_id' => 15,
                'attribute_id' => 31,
                'value' => '{"en": "Red", "fa": "قرمز"}',
                'sort_order' => 0,
                'created_at' => '2026-07-10 18:52:55',
                'updated_at' => '2026-07-10 18:52:55'
            ],
            [
                'id' => 183,
                'product_id' => 15,
                'attribute_id' => 32,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:52:55',
                'updated_at' => '2026-07-10 18:52:55'
            ],
            [
                'id' => 184,
                'product_id' => 16,
                'attribute_id' => 33,
                'value' => '{"en": "Red", "fa": "قرمز"}',
                'sort_order' => 0,
                'created_at' => '2026-07-10 18:52:56',
                'updated_at' => '2026-07-10 18:52:56'
            ],
            [
                'id' => 185,
                'product_id' => 16,
                'attribute_id' => 34,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:52:56',
                'updated_at' => '2026-07-10 18:52:56'
            ],
            [
                'id' => 186,
                'product_id' => 17,
                'attribute_id' => 35,
                'value' => '{"ar": null, "en": "Red", "fa": "قرمز", "hi": null, "it": null, "tr": null, "zh": null}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:52:57',
                'updated_at' => '2026-07-10 18:53:42'
            ],
            [
                'id' => 187,
                'product_id' => 17,
                'attribute_id' => 36,
                'value' => '{"en": "Blue", "fa": "آبی"}',
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:52:57',
                'updated_at' => '2026-07-10 18:52:57'
            ]
        ]);

    }
}
