<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): product_category
 * Generated at: 2026-07-11 08:54:14
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class ProductCategorySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('product_category')->delete();


        DB::table('product_category')->insert([
            [
                'product_id' => 5,
                'category_id' => 6,
                'is_primary' => 1
            ],
            [
                'product_id' => 6,
                'category_id' => 6,
                'is_primary' => 1
            ],
            [
                'product_id' => 7,
                'category_id' => 6,
                'is_primary' => 1
            ],
            [
                'product_id' => 8,
                'category_id' => 6,
                'is_primary' => 1
            ],
            [
                'product_id' => 9,
                'category_id' => 6,
                'is_primary' => 1
            ],
            [
                'product_id' => 10,
                'category_id' => 7,
                'is_primary' => 1
            ],
            [
                'product_id' => 11,
                'category_id' => 7,
                'is_primary' => 1
            ],
            [
                'product_id' => 12,
                'category_id' => 7,
                'is_primary' => 1
            ],
            [
                'product_id' => 13,
                'category_id' => 7,
                'is_primary' => 1
            ]
        ]);

    }
}
