<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): roles, permissions, role_has_permissions, model_has_roles
 * Generated at: 2026-07-11 09:27:43
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('model_has_roles')->delete();
        DB::table('role_has_permissions')->delete();
        DB::table('permissions')->delete();
        DB::table('roles')->delete();


        DB::table('roles')->insert([
            [
                'id' => 1,
                'name' => 'admin',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 2,
                'name' => 'editor',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 3,
                'name' => 'sales',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 4,
                'name' => 'customer',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 5,
                'name' => 'super_user',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:49',
                'updated_at' => '2026-07-10 18:00:49'
            ]
        ]);

        DB::table('permissions')->insert([
            [
                'id' => 1,
                'name' => 'view products',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 2,
                'name' => 'create products',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 3,
                'name' => 'edit products',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 4,
                'name' => 'delete products',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 5,
                'name' => 'view categories',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 6,
                'name' => 'create categories',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 7,
                'name' => 'edit categories',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 8,
                'name' => 'delete categories',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 9,
                'name' => 'manage product_attributes',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 10,
                'name' => 'view orders',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 11,
                'name' => 'manage orders',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 12,
                'name' => 'cancel orders',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 13,
                'name' => 'export orders',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 14,
                'name' => 'view payments',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 15,
                'name' => 'verify payments',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 16,
                'name' => 'refund payments',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 17,
                'name' => 'view users',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 18,
                'name' => 'create users',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 19,
                'name' => 'edit users',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 20,
                'name' => 'delete users',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 21,
                'name' => 'ban users',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 22,
                'name' => 'manage roles',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 23,
                'name' => 'view pages',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 24,
                'name' => 'manage pages',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 25,
                'name' => 'view posts',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 26,
                'name' => 'manage posts',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 27,
                'name' => 'view events',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 28,
                'name' => 'manage events',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 29,
                'name' => 'manage sliders',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 30,
                'name' => 'manage menus',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 31,
                'name' => 'manage settings',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 32,
                'name' => 'manage redirects',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 33,
                'name' => 'manage newsletters',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 34,
                'name' => 'view reports',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 35,
                'name' => 'export reports',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 36,
                'name' => 'view contact_messages',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 37,
                'name' => 'reply contact_messages',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 38,
                'name' => 'delete contact_messages',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 39,
                'name' => 'view coupons',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 40,
                'name' => 'manage coupons',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 41,
                'name' => 'view reviews',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 42,
                'name' => 'manage reviews',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ],
            [
                'id' => 43,
                'name' => 'approve reviews',
                'guard_name' => 'web',
                'created_at' => '2026-07-10 18:00:48',
                'updated_at' => '2026-07-10 18:00:48'
            ]
        ]);

        DB::table('role_has_permissions')->insert([
            [
                'permission_id' => 1,
                'role_id' => 1
            ],
            [
                'permission_id' => 1,
                'role_id' => 2
            ],
            [
                'permission_id' => 1,
                'role_id' => 3
            ],
            [
                'permission_id' => 1,
                'role_id' => 4
            ],
            [
                'permission_id' => 2,
                'role_id' => 1
            ],
            [
                'permission_id' => 2,
                'role_id' => 2
            ],
            [
                'permission_id' => 3,
                'role_id' => 1
            ],
            [
                'permission_id' => 3,
                'role_id' => 2
            ],
            [
                'permission_id' => 3,
                'role_id' => 3
            ],
            [
                'permission_id' => 4,
                'role_id' => 1
            ],
            [
                'permission_id' => 5,
                'role_id' => 1
            ],
            [
                'permission_id' => 5,
                'role_id' => 2
            ],
            [
                'permission_id' => 5,
                'role_id' => 3
            ],
            [
                'permission_id' => 5,
                'role_id' => 4
            ],
            [
                'permission_id' => 6,
                'role_id' => 1
            ],
            [
                'permission_id' => 6,
                'role_id' => 2
            ],
            [
                'permission_id' => 7,
                'role_id' => 1
            ],
            [
                'permission_id' => 7,
                'role_id' => 2
            ],
            [
                'permission_id' => 8,
                'role_id' => 1
            ],
            [
                'permission_id' => 9,
                'role_id' => 1
            ],
            [
                'permission_id' => 9,
                'role_id' => 2
            ],
            [
                'permission_id' => 10,
                'role_id' => 1
            ],
            [
                'permission_id' => 10,
                'role_id' => 2
            ],
            [
                'permission_id' => 10,
                'role_id' => 3
            ],
            [
                'permission_id' => 10,
                'role_id' => 4
            ],
            [
                'permission_id' => 11,
                'role_id' => 1
            ],
            [
                'permission_id' => 11,
                'role_id' => 3
            ],
            [
                'permission_id' => 12,
                'role_id' => 1
            ],
            [
                'permission_id' => 12,
                'role_id' => 3
            ],
            [
                'permission_id' => 13,
                'role_id' => 1
            ],
            [
                'permission_id' => 13,
                'role_id' => 3
            ],
            [
                'permission_id' => 14,
                'role_id' => 1
            ],
            [
                'permission_id' => 14,
                'role_id' => 3
            ],
            [
                'permission_id' => 15,
                'role_id' => 1
            ],
            [
                'permission_id' => 15,
                'role_id' => 3
            ],
            [
                'permission_id' => 16,
                'role_id' => 1
            ],
            [
                'permission_id' => 17,
                'role_id' => 1
            ],
            [
                'permission_id' => 18,
                'role_id' => 1
            ],
            [
                'permission_id' => 19,
                'role_id' => 1
            ],
            [
                'permission_id' => 20,
                'role_id' => 1
            ],
            [
                'permission_id' => 21,
                'role_id' => 1
            ],
            [
                'permission_id' => 22,
                'role_id' => 1
            ],
            [
                'permission_id' => 23,
                'role_id' => 1
            ],
            [
                'permission_id' => 23,
                'role_id' => 2
            ],
            [
                'permission_id' => 24,
                'role_id' => 1
            ],
            [
                'permission_id' => 24,
                'role_id' => 2
            ],
            [
                'permission_id' => 25,
                'role_id' => 1
            ],
            [
                'permission_id' => 25,
                'role_id' => 2
            ],
            [
                'permission_id' => 26,
                'role_id' => 1
            ],
            [
                'permission_id' => 26,
                'role_id' => 2
            ],
            [
                'permission_id' => 27,
                'role_id' => 1
            ],
            [
                'permission_id' => 27,
                'role_id' => 2
            ],
            [
                'permission_id' => 28,
                'role_id' => 1
            ],
            [
                'permission_id' => 28,
                'role_id' => 2
            ],
            [
                'permission_id' => 29,
                'role_id' => 1
            ],
            [
                'permission_id' => 29,
                'role_id' => 2
            ],
            [
                'permission_id' => 30,
                'role_id' => 1
            ],
            [
                'permission_id' => 30,
                'role_id' => 2
            ],
            [
                'permission_id' => 31,
                'role_id' => 1
            ],
            [
                'permission_id' => 32,
                'role_id' => 1
            ],
            [
                'permission_id' => 33,
                'role_id' => 1
            ],
            [
                'permission_id' => 34,
                'role_id' => 1
            ],
            [
                'permission_id' => 34,
                'role_id' => 3
            ],
            [
                'permission_id' => 35,
                'role_id' => 1
            ],
            [
                'permission_id' => 35,
                'role_id' => 3
            ],
            [
                'permission_id' => 36,
                'role_id' => 1
            ],
            [
                'permission_id' => 36,
                'role_id' => 3
            ],
            [
                'permission_id' => 37,
                'role_id' => 1
            ],
            [
                'permission_id' => 37,
                'role_id' => 3
            ],
            [
                'permission_id' => 38,
                'role_id' => 1
            ],
            [
                'permission_id' => 39,
                'role_id' => 1
            ],
            [
                'permission_id' => 39,
                'role_id' => 3
            ],
            [
                'permission_id' => 40,
                'role_id' => 1
            ],
            [
                'permission_id' => 40,
                'role_id' => 3
            ],
            [
                'permission_id' => 41,
                'role_id' => 1
            ],
            [
                'permission_id' => 41,
                'role_id' => 2
            ],
            [
                'permission_id' => 41,
                'role_id' => 3
            ],
            [
                'permission_id' => 41,
                'role_id' => 4
            ],
            [
                'permission_id' => 42,
                'role_id' => 1
            ],
            [
                'permission_id' => 43,
                'role_id' => 1
            ],
            [
                'permission_id' => 43,
                'role_id' => 2
            ]
        ]);

        DB::table('model_has_roles')->insert([
            [
                'role_id' => 1,
                'model_type' => 'App\\Models\\User',
                'model_id' => 22
            ],
            [
                'role_id' => 1,
                'model_type' => 'App\\Models\\User',
                'model_id' => 23
            ],
            [
                'role_id' => 5,
                'model_type' => 'App\\Models\\User',
                'model_id' => 23
            ]
        ]);

    }
}
