<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): sliders
 * Generated at: 2026-07-11 08:54:15
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class SliderSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('sliders')->delete();


        DB::table('sliders')->insert([
            [
                'id' => 1,
                'title' => '{"ar": "تصدير الحجر إلى ٥ قارات", "en": "Exporting Stone to 5 Continents", "fa": "صادرات سنگ به ۵ قاره دنیا", "hi": "5 महाद्वीपों में पत्थर निर्यात", "it": "Esportazione di Pietra in 5 Continenti"}',
                'subtitle' => '{"ar": "أحجار إيران الطبيعية", "en": "Iran\'s Natural Stones", "fa": "سنگ‌های طبیعی ایران", "hi": "ईरान के प्राकृतिक पत्थर", "it": "Pietre Naturali dell\'Iran"}',
                'button_text' => '{"ar": "عرض المنتجات", "en": "View Products", "fa": "مشاهده محصولات", "hi": "उत्पाद देखें", "it": "Vedi Prodotti"}',
                'button_link' => '/products',
                'description' => null,
                'button_target' => '_self',
                'image' => null,
                'mobile_image' => null,
                'video' => null,
                'type' => 'image',
                'overlay_color' => '#000000',
                'overlay_opacity' => 30,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-07-10 18:00:50',
                'updated_at' => '2026-07-10 18:00:50'
            ],
            [
                'id' => 2,
                'title' => '{"ar": "أفضل أحجار إيران المعدنية", "en": "Best Natural Stones of Iran", "fa": "بهترین سنگ‌های معدنی ایران", "hi": "ईरान के सर्वश्रेष्ठ खनिज पत्थर", "it": "Le Migliori Pietre Naturali dell\'Iran"}',
                'subtitle' => '{"ar": "تراورتين، رخام، جرانيت وأحجار طبيعية متميزة", "en": "Travertine, Marble, Granite and Premium Natural Stones", "fa": "تراورتن، مرمریت، گرانیت و سنگ‌های طبیعی برتر", "hi": "ट्रैवर्टाइन, मार्बल, ग्रेनाइट और प्रीमियम प्राकृतिक पत्थर", "it": "Travertino, Marmo, Granito e Pietre Naturali Premium"}',
                'button_text' => '{"ar": "اتصل بنا", "en": "Contact Us", "fa": "تماس با ما", "hi": "संपर्क करें", "it": "Contattaci"}',
                'button_link' => '/contact',
                'description' => null,
                'button_target' => '_self',
                'image' => null,
                'mobile_image' => null,
                'video' => null,
                'type' => 'image',
                'overlay_color' => '#000000',
                'overlay_opacity' => 30,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-07-10 18:00:52',
                'updated_at' => '2026-07-10 18:00:52'
            ]
        ]);

    }
}
