<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by: php artisan db:dump-seeders
 * Source table(s): translation_caches
 * Generated at: 2026-07-11 09:27:43
 *
 * This file was regenerated from the live database contents.
 * Any hand-written structure that was here before has been replaced.
 */
class TranslationCacheSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('translation_caches')->delete();


        DB::table('translation_caches')->insert([
            [
                'id' => 7,
                'source_hash' => 'b2d41ef1d45b0b2667d425826c1e2d05db408ea0709deec491fc1e43e4ecf2c8',
                'source_locale' => 'fa',
                'target_locale' => 'en',
                'context' => 'text',
                'source_text' => 'این یک پاراگراف توضیحات کامل محصول است.
این پاراگراف دوم است.',
                'translated_text' => 'This is a full product description paragraph.
This is the second paragraph.',
                'created_at' => '2026-07-10 18:54:17',
                'updated_at' => '2026-07-10 18:54:17'
            ],
            [
                'id' => 6,
                'source_hash' => 'd411ab1f9bd6affa2de9998ce6cd492dac6a5b35ff964a1ac792c8a46517effd',
                'source_locale' => 'fa',
                'target_locale' => 'en',
                'context' => 'text',
                'source_text' => 'یک توضیح کوتاه برای تست ترجمه خودکار',
                'translated_text' => 'A short explanation for automatic translation testing',
                'created_at' => '2026-07-10 18:54:14',
                'updated_at' => '2026-07-10 18:54:14'
            ],
            [
                'id' => 8,
                'source_hash' => '2c4aaffc4333d929e11963644b2d08f151f13bed79a336b046e40a5ead4bd98f',
                'source_locale' => 'fa',
                'target_locale' => 'hi',
                'context' => 'text',
                'source_text' => 'محصول تست نمونه اتوماتیک',
                'translated_text' => 'स्वचालित नमूना परीक्षण उत्पाद',
                'created_at' => '2026-07-10 18:54:20',
                'updated_at' => '2026-07-10 18:54:20'
            ],
            [
                'id' => 9,
                'source_hash' => '85ad9ee25718ff6cfb6e14bb713e40532db70538fbd1cd77d7db5bc8c5058861',
                'source_locale' => 'fa',
                'target_locale' => 'hi',
                'context' => 'text',
                'source_text' => 'یک توضیح کوتاه برای تست ترجمه خودکار',
                'translated_text' => 'स्वचालित अनुवाद परीक्षण के लिए एक संक्षिप्त विवरण',
                'created_at' => '2026-07-10 18:54:20',
                'updated_at' => '2026-07-10 18:54:20'
            ],
            [
                'id' => 10,
                'source_hash' => '5b9159e4f6fe8c3bc661a5bf96ddc6ae1eaf1076e83d64add2cb653bcdf695e9',
                'source_locale' => 'fa',
                'target_locale' => 'hi',
                'context' => 'text',
                'source_text' => 'این یک پاراگراف توضیحات کامل محصول است.
این پاراگراف دوم است.',
                'translated_text' => 'यह संपूर्ण उत्पाद विवरण पैराग्राफ है.
यह दूसरा पैराग्राफ है.',
                'created_at' => '2026-07-10 18:54:27',
                'updated_at' => '2026-07-10 18:54:27'
            ],
            [
                'id' => 11,
                'source_hash' => '72b0a82d4db5a14f278cd6d8e4d97025d06b21ef70dd1fffb911e43465059831',
                'source_locale' => 'fa',
                'target_locale' => 'it',
                'context' => 'text',
                'source_text' => 'محصول تست نمونه اتوماتیک',
                'translated_text' => 'Prodotto per test campione automatico',
                'created_at' => '2026-07-10 18:54:30',
                'updated_at' => '2026-07-10 18:54:30'
            ],
            [
                'id' => 12,
                'source_hash' => '594a579bf7a7319a255990e331e1ca5e49ee66f3929c431cc8be129779f59b08',
                'source_locale' => 'fa',
                'target_locale' => 'it',
                'context' => 'text',
                'source_text' => 'یک توضیح کوتاه برای تست ترجمه خودکار',
                'translated_text' => 'Una breve spiegazione per il test di traduzione automatica',
                'created_at' => '2026-07-10 18:54:30',
                'updated_at' => '2026-07-10 18:54:30'
            ],
            [
                'id' => 13,
                'source_hash' => '993aa4f95a348fdfb9fd2fa8fb48da91e4946186bbaabf09e48652969eac5ec8',
                'source_locale' => 'fa',
                'target_locale' => 'it',
                'context' => 'text',
                'source_text' => 'این یک پاراگراف توضیحات کامل محصول است.
این پاراگراف دوم است.',
                'translated_text' => 'Questo è un paragrafo con la descrizione completa del prodotto.
Questo è il secondo paragrafo.',
                'created_at' => '2026-07-10 18:54:35',
                'updated_at' => '2026-07-10 18:54:35'
            ],
            [
                'id' => 14,
                'source_hash' => 'c6f2dd9f2e2ab6abaf5bdbd66e447cbbe418eceb1e0a872bf1921a56eed6bd5b',
                'source_locale' => 'fa',
                'target_locale' => 'ar',
                'context' => 'text',
                'source_text' => 'محصول تست نمونه اتوماتیک',
                'translated_text' => 'منتج اختبار العينة التلقائي',
                'created_at' => '2026-07-10 18:54:37',
                'updated_at' => '2026-07-10 18:54:37'
            ],
            [
                'id' => 15,
                'source_hash' => 'a63d25d2a3e5e26181c315a2b2b60e4b0bed35cb1f6d8c03eefced1bebce8759',
                'source_locale' => 'fa',
                'target_locale' => 'ar',
                'context' => 'text',
                'source_text' => 'یک توضیح کوتاه برای تست ترجمه خودکار',
                'translated_text' => 'شرح مختصر لاختبار الترجمة الآلية',
                'created_at' => '2026-07-10 18:54:37',
                'updated_at' => '2026-07-10 18:54:37'
            ],
            [
                'id' => 16,
                'source_hash' => 'b3ccf474ea716a10634d5b2471ff96d3bd006215fb822ae17b4d8c79c73fcb58',
                'source_locale' => 'fa',
                'target_locale' => 'ar',
                'context' => 'text',
                'source_text' => 'این یک پاراگراف توضیحات کامل محصول است.
این پاراگراف دوم است.',
                'translated_text' => 'هذه فقرة وصف المنتج كاملة.
هذه هي الفقرة الثانية.',
                'created_at' => '2026-07-10 18:54:39',
                'updated_at' => '2026-07-10 18:54:39'
            ],
            [
                'id' => 17,
                'source_hash' => '8f016f37b55c9be33d57dba329bd0ef1c194fd34f9e783d2b515aec7765be1cb',
                'source_locale' => 'fa',
                'target_locale' => 'zh',
                'context' => 'text',
                'source_text' => 'محصول تست نمونه اتوماتیک',
                'translated_text' => '自动样品测试产品',
                'created_at' => '2026-07-10 18:54:40',
                'updated_at' => '2026-07-10 18:54:40'
            ],
            [
                'id' => 18,
                'source_hash' => 'd331fae3e3d41196e80e26ffa5180985d6d23323fca3187ae187b2342ea4390d',
                'source_locale' => 'fa',
                'target_locale' => 'zh',
                'context' => 'text',
                'source_text' => 'یک توضیح کوتاه برای تست ترجمه خودکار',
                'translated_text' => '自动翻译测试的简短说明',
                'created_at' => '2026-07-10 18:54:40',
                'updated_at' => '2026-07-10 18:54:40'
            ],
            [
                'id' => 19,
                'source_hash' => '4c0f1541fed4097e7245e6f607029b0f75de3e528485f6b96b5c2466abc5c3b5',
                'source_locale' => 'fa',
                'target_locale' => 'zh',
                'context' => 'text',
                'source_text' => 'این یک پاراگراف توضیحات کامل محصول است.
این پاراگراف دوم است.',
                'translated_text' => '这是完整的产品描述段落。
这是第二段。',
                'created_at' => '2026-07-10 18:54:46',
                'updated_at' => '2026-07-10 18:54:46'
            ],
            [
                'id' => 20,
                'source_hash' => '52e83831502c816f167f1a2f4d5bdd700eabbafd8c61132f5f70e1c0f42f48b7',
                'source_locale' => 'fa',
                'target_locale' => 'tr',
                'context' => 'text',
                'source_text' => 'محصول تست نمونه اتوماتیک',
                'translated_text' => 'Otomatik numune test ürünü',
                'created_at' => '2026-07-10 18:54:48',
                'updated_at' => '2026-07-10 18:54:48'
            ],
            [
                'id' => 21,
                'source_hash' => 'ff725081254f0ede3d41dcfd3b5ccc90f58ad4f88f942c2dfc791d552661a666',
                'source_locale' => 'fa',
                'target_locale' => 'tr',
                'context' => 'text',
                'source_text' => 'یک توضیح کوتاه برای تست ترجمه خودکار',
                'translated_text' => 'Otomatik çeviri testi için kısa bir açıklama',
                'created_at' => '2026-07-10 18:54:48',
                'updated_at' => '2026-07-10 18:54:48'
            ],
            [
                'id' => 22,
                'source_hash' => '57d26243b603292fcecb0bb936833c363241fdfb8b5049e200ea284f068e7c62',
                'source_locale' => 'fa',
                'target_locale' => 'tr',
                'context' => 'text',
                'source_text' => 'این یک پاراگراف توضیحات کامل محصول است.
این پاراگراف دوم است.',
                'translated_text' => 'Bu tam bir ürün açıklama paragrafıdır.
Bu ikinci paragraf.',
                'created_at' => '2026-07-10 18:54:50',
                'updated_at' => '2026-07-10 18:54:50'
            ]
        ]);

    }
}
